### ISSUE TITLE
Add copyright details for every 500px image

### ISSUE THREAD

**Issue by mareri** [spotithyperisland/spot-it#20]
According to 500px policy one have to give and show credit to the creator/owner of the photo. 

Provide attribution credit to the copyright owner (Photographer member of 500px) as well as a hyperlink to 500px website photo page adjacent to each use. Format for credit should read as "© Photographer Name / 500px"

**Comment by abenezerabebe** [comment]
Given: Mack selects an activity type;
When: Mack selects one spot
Then: Mack can see "© Photographer Name / 500px" and if Mack clicks on the image, it redirects to the 500px website photo page;
